US013 - Add new Capability
michaltangri/kainosacademy-project-frontend pull request #23
Opened 2021-08-30 13:51 UTC by TheoHodges

As an Admin
I want to be able to create a new capability and assign it existing bands
So that I can keep the system up to date

Acceptance criteria

- Able to add a role into a new capability
- Able to define:
 - New capability name

2021-08-30 13:55 UTC, sebastianczajkowski requested changes
Is not having any validation intended?

2021-08-30 13:57 UTC, TheoHodges commented
> Is not having any validation intended?
What validation would you be looking for?

2021-08-30 14:57 UTC, jkelso662 requested changes

2021-08-30 14:57 UTC, jkelso662 commented on tests/capability.test.js
> +
Lots of white space here. The only white space I would want in this class is between tests, or if you wanted to separate the three steps of a test out within a test function: setup, call, assert.

E.g. 
```
test("something", async () => {
    setup ...
    setup ...

    something.call ...

    assert ...
    assert ...
}
```

2021-08-31 09:11 UTC, mactrz approved these changes
Looks good

2021-08-31 10:31 UTC, sebastianczajkowski commented on services/capabilityService.js
> +        capabilities.forEach(function (capability) {
Just a heads-up - current solution is fine but costly, below is what I would do

You could use a method that searches for one specific capability by name and if it doesn't find anything, then let the user create a new one, but if it returns a capability, then show the user an error.

2021-08-31 10:33 UTC, sebastianczajkowski approved these changes
The solution I provided is completely optional, so it's good as it is

2021-08-31 10:33 UTC, TheoHodges commented on services/capabilityService.js
> +        capabilities.forEach(function (capability) {
I think I will make this change

2021-08-31 13:44 UTC, jkelso662 approved these changes
Much better! 🤠

2021-08-31 14:13 UTC, closed without merging