012 add role to existing
michaltangri/kainosacademy-project-frontend pull request #26
Opened 2021-08-31 13:48 UTC by michaltangri

As an Admin
I want to add a new role to an existing capability and band
So that I can keep the software information up to date

Acceptance criteria

- Able to add a new role to an existing band and capability
- Able to define band for new role
- Able to define capability for new role
- Able to add details to new role: 
 - Job role name
 - Job spec summary

2021-08-31 14:10 UTC, jkelso662 requested changes
Mostly styling related issues. To avoid these in the future, please take the time to install a linter to pickup on these small styling issues.

2021-08-31 14:10 UTC, jkelso662 commented on routes/jobRoleRoutes.js
> +
Would remove **_only_** line 12. Don't go removing all the white space on me again 😂

2021-08-31 14:10 UTC, jkelso662 commented on routes/jobRoleRoutes.js
> +    /*
Block comments like this tend to sit above the function signature (i.e. above line 19)

2021-08-31 14:10 UTC, jkelso662 commented on routes/jobRoleRoutes.js
> +    let roleData = req.body;
Consider refactoring out at least lines 25 - 30 into another function.

2021-08-31 14:10 UTC, jkelso662 commented on routes/jobRoleRoutes.js
> +    delete roleData.capabilityName;
Make sure these delete operations are needed. In javascript, delete operations are rather intensive computationally.

2021-08-31 14:10 UTC, jkelso662 commented on tests/jobRole.test.js
> +
Remove all whitespace inside these two tests so that only 1x white space line divides the setup from the call from the expect logical blocks of code.

2021-08-31 14:10 UTC, jkelso662 commented on views/addJobRole.njk
> +    <div class="alert alert-danger">{{error}}</div>
I believe there are issues with indentation throughout this file.

2021-08-31 14:10 UTC, jkelso662 commented on views/templates/template.njk
> +
Definately no double white space in HTML.

2021-08-31 14:26 UTC, michaltangri commented
@jkelso662 I think all styling issues are now fixed.

2021-08-31 14:36 UTC, jkelso662 requested changes

2021-08-31 14:36 UTC, jkelso662 commented on views/templates/template.njk
> +                                <li class="nav-item"><a class="nav-link" href="/capabilities">Capability</a></li>
I think these list items should all be the same indentation? No?

2021-08-31 14:37 UTC, TheoHodges approved these changes

2021-09-02 06:42 UTC, michaltangri commented on views/templates/template.njk
> +                                <li class="nav-item"><a class="nav-link" href="/capabilities">Capability</a></li>
![image](https://user-images.githubusercontent.com/88448258/131794669-e2ba2349-09e8-47f6-b329-a17a22f74b0a.png)
They are in my editor 😂
I think somehow two of these were indented using spaces, and others using tabs. Should be fixed now!

2021-09-02 06:47 UTC, sebastianczajkowski approved these changes

2021-09-02 08:49 UTC, merged