023 delete job family
michaltangri/kainosacademy-project-frontend pull request #46
Opened 2021-09-06 11:34 UTC by CKindred

As an Admin
I want to delete a job family
So that I can keep the Career Lattice information up to date

Acceptance Criteria

- Job family deleted

Design consideration:

- Cannot delete job family until all roles within have been deleted?
 - cascading delete solves this

2021-09-06 12:46 UTC, TheoHodges commented on routes/jobFamilyRoutes.js
> +router.delete("/:jobFamilyName", async (req, res) => {
What if we have 2 job families with the same name under different capabilities?

2021-09-06 14:46 UTC, mactrz commented on views/jobFamily.njk
> +                    >Delete</button></td>
Maybe adding and svg with a trashcan would look nicer instead of a delete button?

<img width="687" alt="Zrzut ekranu 2021-09-6 o 16 43 20" src="https://user-images.githubusercontent.com/59143429/132233976-0b0d60f8-3b15-471a-b4f2-99bb230ee471.png">
Here is how option to edit looks on my branch.

To get an svg i suggest going to: https://icons.getbootstrap.com/
After finding the one you like you can get it's html code and just put it into the table

2021-09-06 14:47 UTC, mactrz commented
Everything else looks great, nice job 👍

2021-09-06 14:56 UTC, CKindred commented on views/jobFamily.njk
> +                    >Delete</button></td>
Good suggestion, I'll add that. I'm also going to add a confirm pop-up

2021-09-07 07:15 UTC, mactrz approved these changes

2021-09-07 10:08 UTC, TheoHodges requested changes
Just a couple of minor changes but otherwise looks good

2021-09-07 10:08 UTC, TheoHodges commented on selenium/jobFamily.test.js
> +            const deleteBtn = await driver.findElement(webdriver.By.xpath('/html/body/div/div/div/table/tbody/tr[2]/td[3]/a'));
This should probably be a relative path so that the test doesn't fail when records are added/removed in the database. Try something similar to this xPath which I used in jobRole selenium test:
`//td[contains(text(), "I'm sorry for this record in the database I have to test Selenium")]/following-sibling::td[2]/a`

2021-09-07 10:08 UTC, TheoHodges commented on views/jobFamily.njk
> +                    <a href="" onclick="if (confirm('Are you sure you want to delete this job role?')) $.ajax({
You are deleting a job family not a job role. Text on the pop-up needs changing.

2021-09-07 10:20 UTC, CKindred commented on views/jobFamily.njk
> +                    <a href="" onclick="if (confirm('Are you sure you want to delete this job role?')) $.ajax({
Almost and the end of the project and I'm still getting them mixed up! 😫

2021-09-07 12:33 UTC, CKindred commented
The UI tests currently won't work as the login page blocks them. When we merge everything then they should work

2021-09-07 13:13 UTC, TheoHodges approved these changes

2021-09-07 13:24 UTC, merged